### ISSUE TITLE
Pilha com vetor

### ISSUE THREAD

**Issue by alexandresena** [alexandresena/ED012017#1]
Segui o exemplo do livro do Celes, porém na hora de rodar, ocorre
segmentation fault. Não consegui solucionar.

[PilhaComVetor.pdf](https://github.com/alexandresena/ED012017/files/979318/PilhaComVetor.pdf)

**Comment by gvanerven** [comment]
Acredito que essa parte do código

float pilha_pop (Pilha *p) {
float v = p -> vet [--p -> n]; /* Retira o elemento do topo. */
return v; }

deveria ser vet[p-> --n]

**Comment by gvanerven** [comment]
Alias vet[p-> n--]
